### PR TITLE
Handle secret name/namespace edition

### PR DESCRIPTION
**Pull request by titilambert**
The PR handles force k8s secret deletion/create when name or namespace change in the bitwarden secret

### CODE REVIEW

**Comment by Lerentis** [comment]
This is a usecase that i did not consider but makes a lot of sense as well. The other object types (`registry-credential` and `bitwarden-template`) also miss this functionality. would you mind implementing this for them as well? 
If not i will take care of it afterwards before releasing a new version :) 

Thank you very much :bow:

**Comment by titilambert** [comment]
@Lerentis it's ready !

**Comment by Lerentis** [comment]
Thanks @titilambert! 
do i understand you right that you don't want to implement the fix for the behaviour for the other 2 CRDs and i should follow up on that after the merge?

**Comment by titilambert** [comment]
Sorry, I was not clear. I saw a bug, that's why I ask you to wait before merging.
Also, I'm using only secret (no templates), so, I'm not able to really to test the other types.
So, if you can do it for the other resources, it would be perfect.
Thanks !

**Comment by Lerentis** [comment]
Okay thank you very much :+1: 
i will follow up with the other two probably tomorrow and release right after it

**Pull request merged**
