### PR TITLE
feat: add sync with bitwarden before getting a secret

### PR DESCRIPTION
**Pull request by kaotika**
If you change a value in an existing secret, the operator wasn't update this value in the secret until the pod was restarted. The change adds `bw sync` before getting the secret from bitwarden.

Now you can add an annotation, e.g. version or commit sha and the value will be updated

```yaml
apiVersion: "lerentis.uploadfilter24.eu/v1beta4"
kind: BitwardenSecret
metadata:
  name: test-scope
  annotations:
    commit: "asref433c"
spec:
  content:
    - element:
        secretName: public_key
        secretRef: pubKey 
        secretScope: fields
  id: "466fc4b0-ffca-4444-8d88-b59d4de3d928"
  name: "test-scope"
  namespace: "default"
```

### CODE REVIEW

**Comment by Lerentis** [comment]
Hi @kaotika ,
thanks for the implementation as this feature is already on my mind as well. i think it makes more sense to create a periodic sync as a sync for each function call does not scale very well if you have a lot of movement and/or concurrent operations. are you willing to implement this as a periodic background task?

**Comment by kaotika** [comment]
Hi @Lerentis, yes, I can implement a timer.
Additionally it might be useful in some use cases to add an optional sync before getting a secret, togglable from an env var, e.g. FORCE_RESYNC. What do you think?

**Comment by Lerentis** [comment]
> togglable from an env var, e.g. FORCE_RESYNC
in the CRD or in the operator? in the CRD this would definitely make sense 👍

**Comment by kaotika** [comment]
Hi @Lerentis I was very busy the last weeks. Sorry for that.

I implemented a BW_FORCE_SYNC environment variable the triggers a sync before a get explicitly. It's disabled by default.
A second env BW_SYNC_INTERVAL (default is 15 minutes) controls after which time a sync will be done. If you do a sync at timepoint TSYNC and a get is done between time TSYNC+BW_SYNC_INTERVAL no sync will be executed. If the get comes after TSYNC+BW_SYNC_INTERVAL  a sync will be called before the get is performed.
BW_SYNC_INTERVAL is also applied to the CRD timers so each secret should be in sync properly.
Hope this finishes the feature.

**Comment by kaotika** [comment]
Hi @Lerentis, I don't know your versioning policy. Is this a new feature so bumping whould be from v0.7.6 to v0.8.0 or just an improvement so its v0.7.7?

**Comment by Lerentis** [comment]
Hi @kaotika ,
as the operator is still not in a 1.0 condition i would recommend to bump it to v0.8.0.
please also add your changes to the changelog in `Chart.yaml` to be visible in artifacthub

**Comment by kaotika** [comment]
I updated the files.

**Comment by Lerentis** [comment]
I'll hopefully have a look in the evening and then merge/release it. Sorry for the delay

28.09.2023 15:50:35 Matthias Ludwig ***@***.***>:

**Comment by Lerentis** [comment]
Hi @kaotika ,
i reviewed your PR and validated it functional wise. general looks good to me with some small changes. i sadly can not push to your branch, so here is a patch to apply before merging: 

```
From 1439008abaedeb71c41b3ae8baaf9289d6fa649b Mon Sep 17 00:00:00 2001
From: Tobias Trabelsi <lerentis@uploadfilter24.eu>
Date: Thu, 28 Sep 2023 20:52:10 +0200
Subject: [PATCH] downgrade bitwarden cli and fixed Chart.yaml

---
 Dockerfile                               |  2 +-
 charts/bitwarden-crd-operator/Chart.yaml | 14 ++++----------
 2 files changed, 5 insertions(+), 11 deletions(-)

diff --git a/Dockerfile b/Dockerfile
index 55488ec..61968dc 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -8,7 +8,7 @@ ARG PYTHON_VERSION=3.11.5-r0
 ARG PIP_VERSION=23.1.2-r0
 ARG GCOMPAT_VERSION=1.1.0-r1
 ARG LIBCRYPTO_VERSION=3.1.2-r0
-ARG BW_VERSION=2023.7.0
+ARG BW_VERSION=2023.1.0
 
 COPY requirements.txt /requirements.txt
 
diff --git a/charts/bitwarden-crd-operator/Chart.yaml b/charts/bitwarden-crd-operator/Chart.yaml
index bc2cdca..044bf83 100644
--- a/charts/bitwarden-crd-operator/Chart.yaml
+++ b/charts/bitwarden-crd-operator/Chart.yaml
@@ -6,7 +6,7 @@ type: application
 
 version: "v0.8.0"
 
-appVersion: "0.6.5"
+appVersion: "0.7.0"
 
 keywords:
   - operator
@@ -97,14 +97,8 @@ annotations:
   artifacthub.io/changes: |
     - kind: changed
       description: "Take care to sync with bitwarden before getting a secret, added BW_SYNC_INTERVAL and BW_FORCE_SYNC envs to control sync."
-    - kind: changed
-      description: "Updated alpine to 3.18.3"
-    - kind: changed
-      description: "Updated python to 3.11.5-r0"
-    - kind: changed
-      description: "Updated libcrypto3 to 3.1.2-r0"
-    - kind: changed
-      description: "Updated bitwarden cli to v2023.7.0"
+    - kind: fixed
+      description: "Downgrade bitwarden cli due to segfault on newer versions"
   artifacthub.io/images: |
     - name: bitwarden-crd-operator
-      image: ghcr.io/lerentis/bitwarden-crd-operator:0.6.5
+      image: ghcr.io/lerentis/bitwarden-crd-operator:0.7.0
-- 
2.42.0
```
once you applied it we can merge it and release. Thank you very much for writing this. i think this is a great addition to the operator

**Comment by Lerentis** [comment]
as this PR is stale again i will apply the patch from above in another patch and stop the release pipeline before publish.
thanks again for implementing this feature @kaotika

**Pull request merged**
